(() => {
const db=window.supabase.createClient('https://aamstyeeewncmgqdxpoh.supabase.co','sb_publishable_fOzZvfiio6HSaEgplYUgOA_lWy1tbVe');
const show=m=>typeof window.err==='function'?window.err(m):alert(m);const open=h=>window.openModal?.(h);const close=()=>window.closeModal?.();const phone=v=>{let d=String(v||'').replace(/\D/g,'');if(d.startsWith('91')&&d.length===12)d=d.slice(2);return d.length===10?'+91'+d:''};let selected='admin';
function apply(r){selected=r;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.role===r));const title=document.getElementById('loginTitle'),label=document.getElementById('idLabel'),input=document.getElementById('loginId'),pw=document.getElementById('password'),wrap=document.getElementById('passWrap'),signup=document.getElementById('signupBtn'),forgot=document.getElementById('forgotBtn'),hint=document.getElementById('loginHint');if(title)title.textContent=r==='admin'?'Admin Login':r==='customer'?'Customer Login':'Worker Login';if(label)label.textContent=r==='worker'?'Registered Mobile Number':'Email';if(input){input.type=r==='worker'?'tel':'email';input.placeholder=r==='worker'?'Admin-registered mobile number':r==='admin'?'Admin email':'Customer email';}if(wrap)wrap.style.display=r==='worker'?'none':'block';if(pw)pw.required=r!=='worker';if(signup)signup.style.display=r==='customer'?'inline-block':'none';if(forgot)forgot.style.display=r==='worker'?'none':'inline-block';if(hint)hint.textContent=r==='admin'?'Admin: Email + Password.':r==='customer'?'Customer: Email + Password.':'Worker: वही mobile number जो Admin ने Worker section में register किया है — कोई password/OTP नहीं।'}
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>apply(b.dataset.role)));apply('admin');
const form=document.getElementById('loginForm');if(form)form.onsubmit=async e=>{e.preventDefault();document.getElementById('err')?.classList.add('hidden');const id=document.getElementById('loginId').value.trim(),pass=document.getElementById('password').value;try{if(selected==='worker'){const p=phone(id);if(!p)return show('Valid 10-digit registered mobile number डालें।');const r=await db.functions.invoke('worker-login',{body:{phone:p}});if(r.error)return show(r.error.message);if(r.data?.error)return show(r.data.error);if(r.data?.worker){localStorage.setItem('psc_worker_profile',JSON.stringify(r.data.worker));show('Worker number verified. Worker dashboard session architecture is being secured before production access.');return;}return show('Worker login failed');}if(!id||!pass)return show('Email और password दोनों भरें।');const r=await db.auth.signInWithPassword({email:id,password:pass});if(r.error)return show('Invalid email or password');const p=await db.from('profiles').select('role,is_active').eq('id',r.data.user.id).maybeSingle();if(p.error)return show(p.error.message);if(!p.data||p.data.role!==selected)return(await db.auth.signOut(),show('This account is not registered for '+selected+' login.'));if(p.data.is_active===false)return(await db.auth.signOut(),show('This account is inactive.'));await window.enter?.(r.data.user)}catch(x){show(x?.message||'Login failed')}};
const forgot=document.getElementById('forgotBtn');if(forgot)forgot.onclick=async()=>{const email=document.getElementById('loginId').value.trim();if(!email)return show('पहले अपना email डालें।');const r=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)return show(r.error.message);alert('Password reset link आपके email पर भेज दिया गया है।')};
const signup=document.getElementById('signupBtn');if(signup)signup.onclick=()=>open(`<div class="modal-head"><h3>Customer Registration</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Name</label><input id="na"></div><div class="field"><label>Email</label><input id="em" type="email"></div><div class="field"><label>Password</label><input id="pw" type="password"></div><div class="field"><label>Phone</label><input id="ph"></div><div class="field"><label>Address</label><input id="ad"></div></div><button class="primary full" onclick="window.newCustomer()">Create Customer Account</button>`);window.newCustomer=async()=>{const name=document.getElementById('na').value.trim(),email=document.getElementById('em').value.trim(),password=document.getElementById('pw').value,ph=phone(document.getElementById('ph').value),address=document.getElementById('ad').value.trim();if(!name||!email||password.length<8)return show('Name, email और 8+ character password जरूरी है।');const r=await db.auth.signUp({email,password,options:{data:{name,phone:ph,address}}});if(r.error)return show(r.error.message);close();alert('Customer account created. Verify email if required, then Customer Login करें।')};
})();
